### ISSUE TITLE
关于去雨结果

### ISSUE THREAD

**Issue by hellogry** [hongwang01/RCDNet#3]
您好,可否将论文中不同方法的去雨结果发给我，百度网盘似乎以及失效了。感谢~229602421@qq.com

**Comment by hongwang01** [comment]
Sorry, we have deleted it by mistake.  Please refer to the latest download [link](https://pan.baidu.com/s/1L-kRO-8uAtby3NsSCpPaAA) with password as czjo

**Comment by hellogry** [comment]
I want to know about the Rain800 Dataset for the RCDNet draining result.
psnr/ssim
